name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [27, 21]
    container:
      image: erlang:${{ matrix.otp }}

    steps:
    - uses: actions/checkout@v4
    - name: Fix repository ownership
      run: git config --global --add safe.directory /__w/snabbkaffe/snabbkaffe
    - name: Compile and run tests
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y gawk
        make
    - name: Test with concuerror
      run: make concuerror_test
